version: 2
updates:
  - package-ecosystem: cargo
    directory: "/maybe_xml"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "/benchmark"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10