[advisories]
ignore = [
    # criterion.rs is used only for benchmarks
    # Dependency tree:
    # atty 0.2.14
    # └── criterion 0.4.0
    #     └── maybe_xml 0.3.0
    "RUSTSEC-2021-0145",
]

[output]
deny = ["warnings", "yanked", "unsound", "unmaintained"]
quiet = false